a:
  TYPE_OF_REPORT: !!python/tuple
  - 3
  - 40
  - 522
  - 64
b:
  OFS_COMPANY_ID: !!python/tuple
  - 3
  - 74
  - 140
  - 97
  EMPLOYER NAME: !!python/tuple
  - 140
  - 73
  - 521
  - 97
  ADDRESS: !!python/tuple
  - 3
  - 97
  - 256
  - 118
  CITY_TOWN: !!python/tuple
  - 258
  - 97
  - 409
  - 120
  STATE: !!python/tuple
  - 409
  - 97
  - 448
  - 120
  ZIPCODE: !!python/tuple
  - 450
  - 98
  - 522
  - 120
c:
  HQ_UINT_ID: !!python/tuple
  - 2
  - 131
  - 141
  - 153
  HQ_UINT_NAME: !!python/tuple
  - 141
  - 131
  - 523
  - 155
  HQ_UINT_ADDRESS: !!python/tuple
  - 3
  - 153
  - 257
  - 177
  CITY_TOWN: !!python/tuple
  - 258
  - 154
  - 410
  - 178
  STATE: !!python/tuple
  - 409
  - 154
  - 447
  - 176
  ZIP_STATE: !!python/tuple
  - 449
  - 155
  - 521
  - 177
d:
  EIN: !!python/tuple
  - 2
  - 177
  - 522
  - 196
ef:
  SECTION_E_AND_F: !!python/tuple
  - 2
  - 196
  - 523
  - 264
g:
  NAICS: !!python/tuple
  - 2
  - 264
  - 522
  - 281
h:
  TABLE: !!python/tuple
  - 153
  - 413
  - 522
  - 542
  CURRENT_YEAR_REPORTING_TOTAL_LABEL: !!python/tuple
  - 2
  - 496
  - 153
  - 519
  PRIOR_YEAR_REPORTING_TOTAL_LABEL: !!python/tuple
   - 2
   - 520
   - 153
   - 540
i:
  PERIOD: !!python/tuple
  - 2
  - 540
  - 522
  - 561
j:
  COMMENT: !!python/tuple
  - 2
  - 560
  - 522
  - 672
k:
  OFS_COMPANY_ID: !!python/tuple
  - 2
  - 64
  - 133
  - 89
  EMPLOYER NAME: !!python/tuple
  - 131
  - 65
  - 522
  - 91
  ADDRESS: !!python/tuple
  - 2
  - 88
  - 250
  - 113
  CITY_TOWN: !!python/tuple
  - 402
  - 90
  - 442
  - 113
  STATE: !!python/tuple
  - 403
  - 90
  - 443
  - 114
  ZIPCODE: !!python/tuple
  - 442
  - 90
  - 522
  - 114
  COMMENTS: !!python/tuple
  - 2
  - 124
  - 522
  - 521
  DATE_OF_CERTIFICATION: !!python/tuple
  - 2
  - 562
  - 521
  - 590
  NAME_OF_OFFICAL: !!python/tuple
  - 2
  - 599
  - 131
  - 631
  TITLE_OF_OFFICAL: !!python/tuple
  - 132
  - 597
  - 262
  - 631
  EMAIL_OF_OFFICAL: !!python/tuple
  - 261
  - 599
  - 402
  - 630
  TELEPHONE_OF_OFFICAL: !!python/tuple
  - 402
  - 599
  - 521
  - 632
  NAME_OF_POC: !!python/tuple
  - 2
  - 639
  - 132
  - 674
  TITLE_AND_EMPLOYER_OF_POC: !!python/tuple
  - 133
  - 642
  - 262
  - 674
  EMAIL_OF_POC: !!python/tuple
  - 261
  - 642
  - 403
  - 674
  TELEPHONE_OF_POC: !!python/tuple
  - 402
  - 640
  - 523
  - 674