Employer Is Eligible to File: !!python/tuple
  - 190
  - 632
  - 200
  - 640

Employer Is Not Eligible to File: !!python/tuple
  - 548
  - 634
  - 558
  - 642

Employer No Longer in Business: !!python/tuple
  - 938
  - 634
  - 948
  - 642

Single-Establishment Employer is Federal Contractor: !!python/tuple
  - 203
  - 729
  - 213
  - 737

Multi-Establishment Employer is Federal Contractor: !!python/tuple
  - 799
  - 729
  - 809
  - 737

Headquarters is Federal Contractor: !!python/tuple
  - 82
  - 766
  - 92
  - 774

Non-Headquarters Establishment is Federal Contractor: !!python/tuple
  - 508
  - 766
  - 518
  - 774

One or More Non-Headquarters Establishment is Federal Contractor: !!python/tuple
  - 941
  - 766
  - 951
  - 774