a:
  TYPE_OF_REPORT: !!python/tuple
  - 3
  - 36
  - 521
  - 59
b:
  OFS_COMPANY_ID: !!python/tuple
  - 3
  - 68
  - 140
  - 91
  EMPLOYER NAME: !!python/tuple
  - 140
  - 68
  - 521
  - 91
  ADDRESS: !!python/tuple
  - 3
  - 92
  - 256
  - 114
  CITY_TOWN: !!python/tuple
  - 258
  - 92
  - 409
  - 114
  STATE: !!python/tuple
  - 409
  - 92
  - 448
  - 114
  ZIPCODE: !!python/tuple
  - 450
  - 92
  - 522
  - 114
c:
  HQ_UINT_ID: !!python/tuple
  - 2
  - 125
  - 141
  - 147
  HQ_UINT_NAME: !!python/tuple
  - 141
  - 125
  - 523
  - 147
  HQ_UINT_ADDRESS: !!python/tuple
  - 3
  - 150
  - 257
  - 172
  CITY_TOWN: !!python/tuple
  - 258
  - 150
  - 410
  - 172
  STATE: !!python/tuple
  - 409
  - 150
  - 447
  - 172
  ZIP_STATE: !!python/tuple
  - 449
  - 150
  - 521
  - 172
d:
  EIN: !!python/tuple
  - 2
  - 173
  - 522
  - 192
ef:
  SECTION_E_AND_F: !!python/tuple
  - 2
  - 192
  - 521
  - 277
g:
  NAICS: !!python/tuple
  - 2
  - 279
  - 522
  - 294
h:
  TABLE: !!python/tuple
  - 152
  - 428
  - 522
  - 547
  CURRENT_YEAR_REPORTING_TOTAL_LABEL: !!python/tuple
  -  2
  - 511
  - 153
  - 522
  PRIOR_YEAR_REPORTING_TOTAL_LABEL: !!python/tuple
  -  2
  - 534
  - 153
  - 546
i:
  PERIOD: !!python/tuple
  - 2
  - 546
  - 522
  - 566
j:
  COMMENT: !!python/tuple
  - 2
  - 566
  - 522
  - 678
k:
  OFS_COMPANY_ID: !!python/tuple
  - 2
  - 64
  - 133
  - 89
  EMPLOYER NAME: !!python/tuple
  - 131
  - 65
  - 522
  - 91
  ADDRESS: !!python/tuple
  - 2
  - 88
  - 250
  - 113
  CITY_TOWN: !!python/tuple
  - 402
  - 90
  - 442
  - 113
  STATE: !!python/tuple
  - 403
  - 90
  - 443
  - 114
  ZIPCODE: !!python/tuple
  - 442
  - 90
  - 522
  - 114
  COMMENTS: !!python/tuple
  - 2
  - 124
  - 522
  - 521
  DATE_OF_CERTIFICATION: !!python/tuple
  - 2
  - 562
  - 521
  - 590
  NAME_OF_OFFICAL: !!python/tuple
  - 2
  - 599
  - 131
  - 631
  TITLE_OF_OFFICAL: !!python/tuple
  - 132
  - 597
  - 262
  - 631
  EMAIL_OF_OFFICAL: !!python/tuple
  - 261
  - 599
  - 402
  - 630
  TELEPHONE_OF_OFFICAL: !!python/tuple
  - 402
  - 599
  - 521
  - 632
  NAME_OF_POC: !!python/tuple
  - 2
  - 639
  - 132
  - 674
  TITLE_AND_EMPLOYER_OF_POC: !!python/tuple
  - 133
  - 642
  - 262
  - 674
  EMAIL_OF_POC: !!python/tuple
  - 261
  - 642
  - 403
  - 674
  TELEPHONE_OF_POC: !!python/tuple
  - 402
  - 640
  - 523
  - 674