from .figure_1  import figure_1
from .figure_2  import figure_2
from .figure_3  import figure_3
from .figure_4  import figure_4
from .figure_5  import figure_5
from .figure_6  import figure_6
from .figure_7  import figure_7
from .figure_8  import figure_8
from .figure_9  import figure_9
from .figure_10 import figure_10
from .figure_11 import figure_11
from .figure_12 import figure_12
from .figure_13 import figure_13
