eeo1:
  0: !!python/tuple
    - "a"
    - "b"
    - "c"
    - "d"
    - "ef"
    - "g"
    - "h"
    - "i"
    - "j"
eeo5:
  0: !!python/tuple
    - "title"
    - "a"
    - "b"
    - "c"
    - "d"
  1: !!python/tuple
    - "table"