a:
  TYPE_OF_REPORT: !%21python/tuple
  - 2
  - 37
  - 522
  - 61
b:
  OFS_COMPANY_ID: !%21python/tuple
  - 2
  - 70
  - 140
  - 92
  EMPLOYER NAME: !%21python/tuple
  - 140
  - 70
  - 522
  - 92
  ADDRESS: !%21python/tuple
  - 4
  - 93
  - 257
  - 117
  CITY_TOWN: !%21python/tuple
  - 257
  - 93
  - 409
  - 117
  STATE: !%21python/tuple
  - 409
  - 93
  - 448
  - 117
  ZIPCODE: !%21python/tuple
  - 448
  - 93
  - 522
  - 117
d:
  EIN: !%21python/tuple
  - 2
  - 173
  - 522
  - 193
ef:
  SECTION_E_AND_F: !%21python/tuple
  - 2
  - 192
  - 502
  - 280
g:
  NAICS: !%21python/tuple
  - 2
  - 280
  - 522
  - 297
h:
  TABLE: !%21python/tuple
  - 154
  - 430
  - 522
  - 548
i:
  PERIOD: !%21python/tuple
  - 2
  - 548
  - 522
  - 556
j:
  COMMENT: !%21python/tuple
  - 2
  - 566
  - 522
  - 679
k:
  OFS_COMPANY_ID: !%21python/tuple
  - 8
  - 61
  - 153
  - 83
  EMPLOYER NAME: !%21python/tuple
  - 134
  - 62
  - 516
  - 83
  ADDRESS: !%21python/tuple
  - 8
  - 83
  - 248
  - 117
  CITY_TOWN: !%21python/tuple
  - 248
  - 83
  - 398
  - 118
  STATE: !%21python/tuple
  - 397
  - 84
  - 437
  - 118
  ZIPCODE: !%21python/tuple
  - 436
  - 84
  - 515
  - 118
  COMMENTS: !%21python/tuple
  - 8
  - 128
  - 514
  - 452
  DATE_OF_CERTIFICATION: !%21python/tuple
  - 8
  - 494
  - 514
  - 521
  NAME_OF_OFFICAL: !%21python/tuple
  - 8
  - 532
  - 262
  - 565
  TITLE_OF_OFFICAL: !%21python/tuple
  - 262
  - 532
  - 515
  - 565
  EMAIL_OF_OFFICAL: !%21python/tuple
  - 8
  - 565
  - 262
  - 600
  TELEPHONE_OF_OFFICAL: !%21python/tuple
  - 262
  - 566
  - 515
  - 600
  NAME_OF_POC: !%21python/tuple
  - 8
  - 610
  - 262
  - 643
  TITLE_AND_EMPLOYER_OF_POC: !%21python/tuple
  - 263
  - 610
  - 501
  - 642
  EMAIL_OF_POC: !%21python/tuple
  - 8
  - 610
  - 262
  - 642
  TELEPHONE_OF_POC: !%21python/tuple
  - 262
  - 644
  - 501
  - 669
