title:
  CONTROL_NUMBER_YEAR: !!python/tuple
  - 2
  - 80
  - 522
  - 135
a:
  TYPE_OF_GOVERNMENT: !!python/tuple
  - 2
  - 153
  - 522
  - 197
b:
  NAME: !!python/tuple
  - 2
  - 213
  - 523
  - 254
  ADDRESS: !!python/tuple
  - 2
  - 255
  - 168
  - 310
  CITY: !!python/tuple
  - 170
  - 255
  - 276
  - 310
  COUNTY: !!python/tuple
  - 277
  - 255
  - 357
  - 310
  STATE: !!python/tuple
  - 358
  - 255
  - 439
  - 310
  ZIPCODE: !!python/tuple
  - 440
  - 255
  - 521
  - 310
c:
  FUNCTIONS_OTHER: !!python/tuple
  - 282
  - 590
  - 522
  - 650

table:
  a1: !!python/tuple
  - 85
  - 216
  - 116
  - 619
  a2: !!python/tuple
  - 117
  - 216
  - 153
  - 619
  a3: !!python/tuple
  - 153
  - 216
  - 489
  - 619
  a4: !!python/tuple
  - 489
  - 216
  - 522
  - 619
function:
  FUNCTION: !!python/tuple
  - 286
  - 94
  - 522
  - 106
table2:
  a5: !!python/tuple
  - 85
  - 218
  - 117
  - 460
  a6: !!python/tuple
  - 117
  - 218
  - 153
  - 460
  a7: !!python/tuple
  - 153
  - 218
  - 490
  - 460
  a8: !!python/tuple
  - 490
  - 218
  - 522
  - 460
  atotal1: !!python/tuple
  - 85
  - 464
  - 117
  - 476
  atotal2: !!python/tuple
  - 117
  - 464
  - 153
  - 476
  atotal3: !!python/tuple
  - 153
  - 464
  - 490
  - 476
  atotal4: !!python/tuple
  - 490
  - 464
  - 522
  - 476
  bhistm_1: !!python/tuple
    - 85
    - 494
    - 117
    - 503
  bhistf_1: !!python/tuple
    - 126
    - 495
    - 146
    - 502
  brest_1: !!python/tuple
    - 153
    - 494
    - 490
    - 503
  btotal_1: !!python/tuple
    - 490
    - 494
    - 522
    - 503
  bhistm_2: !!python/tuple
    - 85
    - 506
    - 117
    - 546
  bhistf_2: !!python/tuple
    - 126
    - 506
    - 146
    - 546
  brest_2: !!python/tuple
    - 153
    - 506
    - 490
    - 546
  btotal_2: !!python/tuple
    - 490
    - 506
    - 522
    - 546
  bhistm_3: !!python/tuple
    - 85
    - 550
    - 117
    - 559
  bhistf_3: !!python/tuple
    - 126
    - 550
    - 146
    - 559
  brest_3: !!python/tuple
    - 153
    - 550
    - 490
    - 559
  btotal_3: !!python/tuple
    - 490
    - 550
    - 522
    - 559
  bhistm_4: !!python/tuple
    - 85
    - 562
    - 117
    - 573
  bhistf_4: !!python/tuple
    - 126
    - 562
    - 146
    - 573
  brest_4: !!python/tuple
    - 153
    - 562
    - 490
    - 573
  btotal_4: !!python/tuple
    - 490
    - 562
    - 522
    - 573
  bhistm_5: !!python/tuple
    - 85
    - 577
    - 117
    - 587
  bhistf_5: !!python/tuple
    - 126
    - 577
    - 146
    - 587
  brest_5: !!python/tuple
    - 153
    - 577
    - 490
    - 587
  btotal_5: !!python/tuple
    - 490
    - 577
    - 522
    - 587
  bhistm_total: !!python/tuple
    - 85
    - 597
    - 117
    - 609
  bhistf_total: !!python/tuple
    - 126
    - 597
    - 146
    - 609
  brest_total: !!python/tuple
    - 153
    - 597
    - 490
    - 609
  btotal_total: !!python/tuple
    - 490
    - 597
    - 522
    - 609
table3:
  chistm_1: !!python/tuple
    - 85
    - 200
    - 117
    - 209
  chistf_1: !!python/tuple
    - 126
    - 200
    - 146
    - 209
  crest_1: !!python/tuple
    - 153
    - 200
    - 490
    - 209
  ctotal_1: !!python/tuple
    - 490
    - 200
    - 522
    - 209
  chistm_2: !!python/tuple
    - 85
    - 212
    - 117
    - 252
  chistf_2: !!python/tuple
    - 126
    - 212
    - 146
    - 252
  crest_2: !!python/tuple
    - 153
    - 212
    - 490
    - 252
  ctotal_2: !!python/tuple
    - 490
    - 212
    - 522
    - 252
  chistm_3: !!python/tuple
    - 85
    - 256
    - 117
    - 266
  chistf_3: !!python/tuple
    - 126
    - 256
    - 146
    - 266
  crest_3: !!python/tuple
    - 153
    - 256
    - 490
    - 266
  ctotal_3: !!python/tuple
    - 490
    - 256
    - 522
    - 266
  chistm_4: !!python/tuple
    - 85
    - 269
    - 117
    - 279
  chistf_4: !!python/tuple
    - 126
    - 269
    - 146
    - 279
  crest_4: !!python/tuple
    - 153
    - 269
    - 490
    - 279
  ctotal_4: !!python/tuple
    - 490
    - 269
    - 522
    - 279
  chistm_5: !!python/tuple
    - 85
    - 283
    - 117
    - 293
  chistf_5: !!python/tuple
    - 126
    - 283
    - 146
    - 293
  crest_5: !!python/tuple
    - 153
    - 283
    - 490
    - 293
  ctotal_5: !!python/tuple
    - 490
    - 283
    - 522
    - 293
  chistm_total: !!python/tuple
    - 85
    - 303
    - 117
    - 315
  chistf_total: !!python/tuple
    - 126
    - 303
    - 146
    - 315
  crest_total: !!python/tuple
    - 153
    - 303
    - 490
    - 315
  ctotal_total: !!python/tuple
    - 490
    - 303
    - 522
    - 315
e:
  DEPARTMENTS_AGENCIES_INCLUDED: !!python/tuple
  - 2
  - 322
  - 522
  - 417
f:
  DEPARTMENTS_AGENCIES_NOT_INCLUDED: !!python/tuple
  - 2
  - 417
  - 522
  - 522
g:
  REMARKS: !!python/tuple
  - 2
  - 522
  - 522
  - 639