title:
  OE_NUM_AND_YEAR: !!python/tuple
  - 3
  - 94
  - 523
  - 158
a:
  TYPE_OF_AGENCY: !!python/tuple
  - 3
  - 274
  - 523
  - 312
b:
  NAME: !!python/tuple
  - 3
  - 327
  - 523
  - 366
  ADDRESS: !!python/tuple
  - 3
  - 366
  - 196
  - 405
  CITY: !!python/tuple
  - 196
  - 366
  - 277
  - 405
  COUNTY: !!python/tuple
  - 279
  - 366
  - 358
  - 405
  STATE: !!python/tuple
  - 358
  - 366
  - 419
  - 405
  ZIPCODE: !!python/tuple
  - 418
  - 366
  - 523
  - 404
c:
  SCHOOLS_OP: !!python/tuple
  - 2
  - 420
  - 178
  - 471
  ANNEXES_OP: !!python/tuple
  - 178
  - 420
  - 344
  - 473
  OCTOBER_1ST: !!python/tuple
  - 344
  - 420
  - 523
  - 473
d:
  REMARK: !!python/tuple
  - 2
  - 501
  - 523
  - 674
table:
  a1: !!python/tuple
  - 149
  - 213
  - 501
  - 291
  a2: !!python/tuple
  - 149
  - 290
  - 502
  - 307
  a3: !!python/tuple
  - 149
  - 307
  - 502
  - 371
  b: !!python/tuple
  - 149
  - 379
  - 500
  - 405
  c: !!python/tuple
  - 149
  - 415
  - 500
  - 468
