title:
  OE_NUM_AND_YEAR: !!python/tuple
  - 43
  - 178
  - 523
  - 240
a:
  TYPE_OF_AGENCY: !!python/tuple
  - 3
  - 357
  - 523
  - 395
b:
  NAME: !!python/tuple
  - 2
  - 411
  - 523
  - 450
  ADDRESS: !!python/tuple
  - 2
  - 450
  - 196
  - 488
  CITY: !!python/tuple
  - 196
  - 450
  - 279
  - 488
  COUNTY: !!python/tuple
  - 279
  - 450
  - 358
  - 488
  STATE: !!python/tuple
  - 358
  - 450
  - 419
  - 488
  ZIPCODE: !!python/tuple
  - 418
  - 450
  - 523
  - 488
c:
  SCHOOLS_OP: !!python/tuple
  - 2
  - 504
  - 178
  - 555
  ANNEXES_OP: !!python/tuple
  - 178
  - 504
  - 344
  - 555
  OCTOBER_1ST: !!python/tuple
  - 344
  - 504
  - 523
  - 555
d:
  REMARK: !!python/tuple
  - 2
  - 583
  - 523
  - 678
table:
  a1: !!python/tuple
  - 143
  - 276
  - 518
  - 360
  a2: !!python/tuple
  - 143
  - 360
  - 518
  - 377
  a3: !!python/tuple
  - 143
  - 377
  - 518
  - 443
  b: !!python/tuple
  - 143
  - 454
  - 518
  - 481
  c: !!python/tuple
  - 143
  - 492
  - 518
  - 548
