Local Public School: !!python/tuple
  - 111
  - 1074
  - 141
  - 1101

Special Regional Agency: !!python/tuple
  - 396
  - 1074
  - 426
  - 1101

State Education Agency: !!python/tuple
  - 720
  - 1074
  - 750
  - 1101

Other: !!python/tuple
  - 1062
  - 1074
  - 1092
  - 1101
