eeo1:
  0: !!python/tuple
    - "a"
    - "b"
    - "c"
    - "d"
    - "ef"
    - "g"
    - "h"
    - "i"
    - "j"

eeo4:
  0: !!python/tuple
    - "table"
  1: !!python/tuple
    - "function"
    - "table2"
  2: !!python/tuple
    - "table3"
    - "e"
    - "f"
    - "g"

eeo4_cover:
  0: !!python/tuple
    - "title"
    - "a"
    - "b"
    - "c"

eeo4_munis:
  0: !!python/tuple
    - "title"
    - "a"
    - "b"
    - "c"
    - "table1"
  1: !!python/tuple
    - "function"
    - "table2"
  2: !!python/tuple
    - "table3"
  3: !!python/tuple
    - "table4"
    - "e"
    - "f"
    - "g"

eeo5:
  0: !!python/tuple
    - "title"
    - "a"
    - "b"
    - "c"
    - "d"
  1: !!python/tuple
    - "table"