# schema:
# form_type:
#   `part`:
#   - `row_num`
#   - `col_num`

eeo1: !!python/tuple
    - 12
    - 15

eeo4_type1:
#hispanic male row 1-40
  a1: !!python/tuple
    - 40
    - 1
#hispanic female row 1-40
  a2: !!python/tuple
    - 40
    - 1
#non hispanic row 1-40
  a3: !!python/tuple
    - 40
    - 12
#total row 1-40
  a4: !!python/tuple
    - 40
    - 1
#hispanic male row 41-64
  a5: !!python/tuple
    - 24
    - 1
#hispanic female row 41-64
  a6: !!python/tuple
    - 24
    - 1
#non hispanic row 41-64
  a7: !!python/tuple
    - 24
    - 12
#total row 41-64
  a8: !!python/tuple
    - 24
    - 1
#hispanic male row 65
  atotal1: !!python/tuple
    - 1
    - 1
#hispanic female row 65
  atotal2: !!python/tuple
    - 1
    - 1
#non hispanic row 65
  atotal3: !!python/tuple
    - 1
    - 12
#total row 65
  atotal4: !!python/tuple
    - 1
    - 1
#hispanic male row 66
  bhistm_1: !!python/tuple
    - 1
    - 1
#hispanic female row 66
  bhistf_1: !!python/tuple
    - 1
    - 1
#non hispanic row 66
  brest_1: !!python/tuple
    - 1
    - 12
#total row 66
  btotal_1: !!python/tuple
    - 1
    - 1
#hispanic male row 67-70
  bhistm_2: !!python/tuple
    - 4
    - 1
#hispanic female row 67-70
  bhistf_2: !!python/tuple
    - 4
    - 1
#non hispanic row 67-70
  brest_2: !!python/tuple
    - 4
    - 12
#total row 67-70
  btotal_2: !!python/tuple
    - 4
    - 1
#hispanic male row 71
  bhistm_3: !!python/tuple
    - 1
    - 1
#hispanic female row 71
  bhistf_3: !!python/tuple
    - 1
    - 1
#non hispanic row 71
  brest_3: !!python/tuple
    - 1
    - 12
#total row 71
  btotal_3: !!python/tuple
    - 1
    - 1
#hispanic male row 72
  bhistm_4: !!python/tuple
    - 1
    - 1
#hispanic female row 72
  bhistf_4: !!python/tuple
    - 1
    - 1
#non hispanic row 72
  brest_4: !!python/tuple
    - 1
    - 12
#total row 72
  btotal_4: !!python/tuple
    - 1
    - 1
#hispanic male row 73
  bhistm_5: !!python/tuple
    - 1
    - 1
#hispanic female row 73
  bhistf_5: !!python/tuple
    - 1
    - 1
#non hispanic row 73
  brest_5: !!python/tuple
    - 1
    - 12
#total row 73
  btotal_5: !!python/tuple
    - 1
    - 1
#hispanic male row 74
  bhistm_total: !!python/tuple
    - 1
    - 1
#hispanic female row 74
  bhistf_total: !!python/tuple
    - 1
    - 1
#non hispanic row 74
  brest_total: !!python/tuple
    - 1
    - 12
#total row 74
  btotal_total: !!python/tuple
    - 1
    - 1
#hispanic male row 75
  chistm_1: !!python/tuple
    - 1
    - 1
#hispanic female row 75
  chistf_1: !!python/tuple
    - 1
    - 1
#non hispanic row 75
  crest_1: !!python/tuple
    - 1
    - 12
#total row 75
  ctotal_1: !!python/tuple
    - 1
    - 1
#hispanic male row 76-79
  chistm_2: !!python/tuple
    - 4
    - 1
#hispanic female row 76-79
  chistf_2: !!python/tuple
    - 4
    - 1
#non hispanic row 76-79
  crest_2: !!python/tuple
    - 4
    - 12
#total row 76-79
  ctotal_2: !!python/tuple
    - 4
    - 1
#hispanic male row 80
  chistm_3: !!python/tuple
    - 1
    - 1
#hispanic female row 80
  chistf_3: !!python/tuple
    - 1
    - 1
#non hispanic row 80
  crest_3: !!python/tuple
    - 1
    - 12
#total row 80
  ctotal_3: !!python/tuple
    - 1
    - 1
#hispanic male row 81
  chistm_4: !!python/tuple
    - 1
    - 1
#hispanic female row 81
  chistf_4: !!python/tuple
    - 1
    - 1
#non hispanic row 81
  crest_4: !!python/tuple
    - 1
    - 12
#total row 81
  ctotal_4: !!python/tuple
    - 1
    - 1
#hispanic male row 82
  chistm_5: !!python/tuple
    - 1
    - 1
#hispanic female row 82
  chistf_5: !!python/tuple
    - 1
    - 1
#non hispanic row 82
  crest_5: !!python/tuple
    - 1
    - 12
#total row 82
  ctotal_5: !!python/tuple
    - 1
    - 1
#hispanic male row 83
  chistm_total: !!python/tuple
    - 1
    - 1
#hispanic female row 83
  chistf_total: !!python/tuple
    - 1
    - 1
#non hispanic row 83
  crest_total: !!python/tuple
    - 1
    - 12
#total row 83
  ctotal_total: !!python/tuple
    - 1
    - 1

eeo4_type2:
# table1: rows 1-40
# rows 1-8 hispanic male and female
  a1_hisp: !!python/tuple
    - 8
    - 2
# rows 1-8 non hispanic male
  a1_male: !!python/tuple
    - 8
    - 6
# rows 1-8 non hispanic female
  a1_female: !!python/tuple
    - 8
    - 6
# rows 1-8 total
  a1_total: !!python/tuple
    - 8
    - 1
# rows 9-16 hispanic male and female
  a2_hisp: !!python/tuple
    - 8
    - 2
# rows 9-16 non hispanic male
  a2_male: !!python/tuple
    - 8
    - 6
# rows 9-16 non hispanic female
  a2_female: !!python/tuple
    - 8
    - 6
# rows 9-16 total
  a2_total: !!python/tuple
    - 8
    - 1
# rows 17-24 hispanic male and female
  a3_hisp: !!python/tuple
    - 8
    - 2
# rows 17-24 non hispanic male
  a3_male: !!python/tuple
    - 8
    - 6
# rows 17-24 non hispanic female
  a3_female: !!python/tuple
    - 8
    - 6
# rows 17-24 total
  a3_total: !!python/tuple
    - 8
    - 1
# rows 25-32 hispanic male and female
  a4_hisp: !!python/tuple
    - 8
    - 2
# rows 25-32 non hispanic male
  a4_male: !!python/tuple
    - 8
    - 6
# rows 25-32 non hispanic female
  a4_female: !!python/tuple
    - 8
    - 6
# rows 25-32 total
  a4_total: !!python/tuple
    - 8
    - 1
# rows 33-40 hispanic male and female
  a5_hisp: !!python/tuple
    - 8
    - 2
# rows 33-40 non hispanic male
  a5_male: !!python/tuple
    - 8
    - 6
# rows 33-40 non hispanic female
  a5_female: !!python/tuple
    - 8
    - 6
# rows 33-40 total
  a5_total: !!python/tuple
    - 8
    - 1
# table2: rows 41-65
# rows 41-48 hispanic male and female
  a6_hisp: !!python/tuple
    - 8
    - 2
# rows 41-48 non hispanic male
  a6_male: !!python/tuple
    - 8
    - 6
# rows 41-48 non hispanic female
  a6_female: !!python/tuple
    - 8
    - 6
# rows 41-48 total
  a6_total: !!python/tuple
    - 8
    - 1
# rows 49-56 hispanic male and female
  a7_hisp: !!python/tuple
    - 8
    - 2
# rows 49-56 non hispanic male
  a7_male: !!python/tuple
    - 8
    - 6
# rows 49-56 non hispanic female
  a7_female: !!python/tuple
    - 8
    - 6
# rows 49-56 total
  a7_total: !!python/tuple
    - 8
    - 1
# rows 57-64 hispanic male and female
  a8_hisp: !!python/tuple
    - 8
    - 2
# rows 57-64 non hispanic male
  a8_male: !!python/tuple
    - 8
    - 6
# rows 57-64 non hispanic female
  a8_female: !!python/tuple
    - 8
    - 6
# rows 57-64 total
  a8_total: !!python/tuple
    - 8
    - 1
# row 65 hispanic male and female
  atotal_hisp: !!python/tuple
    - 1
    - 2
# row 65 non hispanic male
  atotal_male: !!python/tuple
    - 1
    - 6
# row 65 non hispanic female
  atotal_female: !!python/tuple
    - 1
    - 6
# row 65 total
  atotal_total: !!python/tuple
    - 1
    - 1
# table3: rows 66-74
# rows 66-73 hispanic male and female
  b_hisp: !!python/tuple
    - 8
    - 2
# rows 66-73 non hispanic male
  b_male: !!python/tuple
    - 8
    - 6
# rows 66-73 non hispanic female
  b_female: !!python/tuple
    - 8
    - 6
# rows 66-73 total
  b_total: !!python/tuple
    - 8
    - 1
# row 74 hispanic male and female
  btotal_hisp: !!python/tuple
    - 1
    - 2
# row 74 non hispanic male
  btotal_male: !!python/tuple
    - 1
    - 6
# row 74 non hispanic female
  btotal_female: !!python/tuple
    - 1
    - 6
# row 74 total
  btotal_total: !!python/tuple
    - 1
    - 1
# table4: rows 75-83
# rows 75-82 hispanic male and female
  c_hisp: !!python/tuple
    - 8
    - 2
# rows 75-82 non hispanic male
  c_male: !!python/tuple
    - 8
    - 6
# rows 75-82 non hispanic female
  c_female: !!python/tuple
    - 8
    - 6
# rows 75-82 total
  c_total: !!python/tuple
    - 8
    - 1
# row 83 hispanic male and female
  ctotal_hisp: !!python/tuple
    - 1
    - 2
# row 83 non hispanic male
  ctotal_male: !!python/tuple
    - 1
    - 6
# row 83 non hispanic female
  ctotal_female: !!python/tuple
    - 1
    - 6
# row 83 total
  ctotal_total: !!python/tuple
    - 1
    - 1

eeo5:
  a1: !!python/tuple
    - 10
    - 15
  a2: !!python/tuple
    - 1
    - 15
  a3: !!python/tuple
    - 8
    - 15
  b: !!python/tuple
    - 3
    - 15
  c: !!python/tuple
    - 6
    - 15
